services:
    kode_cms_kode.mobile.service.mobile_detect:
        class: Mobile_Detect

    kode_cms_kode.mobile.twig.mobile_extension:
        class: KodeCms\KodeBundle\Core\Twig\MobileExtension
        public: false
        arguments:
            - '%kode_cms_kode.core.short_functions%'
        tags:
            -
                name: twig.extension
