services:
    kode_cms_kode.script.service.mobile_detect:
        class: '%kode_cms_kode.script.service.mobile_detect.class%'

    kode_cms_kode.script.twig.mobile_extension:
        class: '%kode_cms_kode.script.twig.mobile_extension.class%'
        public: false
        arguments:
            - '%kode_cms_kode.core.short_functions%'
        tags:
            -
                name: twig.extension

    kode_cms_kode.script.twig.country_extension:
        class: '%kode_cms_kode.script.twig.country_extension.class%'
        public: false
        arguments:
            - '@request_stack'
            - '%kode_cms_kode.core.short_functions%'
        tags:
            -
                name: twig.extension
